services:
  web:
    build: .
    container_name: django-sample-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    command: python manage.py runserver 0.0.0.0:8000
